# Generated by Django 6.0 on 2025-12-29 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('base_price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive rooms are hidden from search and cannot be booked.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='bookings_ro_is_acti_71aded_idx'), models.Index(fields=['base_price_per_hour'], name='bookings_ro_base_pr_499c9d_idx'), models.Index(fields=['base_price_per_day'], name='bookings_ro_base_pr_5d5c96_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily')], max_length=10)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked in'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='CONFIRMED', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.room')),
            ],
            options={
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['room', 'start_datetime', 'end_datetime', 'status'], name='bookings_bo_room_id_adf340_idx'), models.Index(fields=['user', 'start_datetime'], name='bookings_bo_user_id_2add19_idx')],
            },
        ),
    ]
