# Generated by Django 6.0 on 2025-12-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='logo',
            field=models.TextField(blank=True, help_text='Base64 encoded image for room / hotel logo'),
        ),
    ]
