# Generated by Django 6.0 on 2025-12-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_room_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at', '-start_datetime']},
        ),
    ]
